services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: attendance123
      MYSQL_DATABASE: smart_classroom
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flask_app:
    build: .
    container_name: attendance_flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=attendance_user
      - MYSQL_PASSWORD=attendance_pass
      - MYSQL_DATABASE=smart_classroom
      - ESP32_IP=192.168.89.42
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: attendance_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: attendance123
    depends_on:
      - mysql
    networks:
      - attendance_network

volumes:
  mysql_data:

networks:
  attendance_network:
    driver: bridge